name: "Repo Pruner"
description: "Scans for inactive branches and creates a summary issue listing their status (merged, unmerged, or without an associated PR) for review."
author: "Armin Broubakarian"

inputs:
  inactive_days:
    description: "Number of days since the last commit before a branch is considered inactive. Branches that haven't had commits in this time frame will be listed in the summary issue. Default is 30."
    required: false
    default: "30"

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: git-branch
  color: green
